version: '3.1'

services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./static/:/just_finance/static/
      - ./media/:/just_finance/media/

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb/:/var/lib/postgresql/data
    env_file: ./.env

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/just_finance
      - ./static/:/just_finance/static/
      - ./media/:/just_finance/media/

    depends_on:
      - "db"
    env_file: ./.env
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - HTTP_PORT=8000

#  redis:
#    image: redis
#    ports:
#      - 6379:6379
#    restart: always
#
#
#  celery:
#    build:
#      context: .
#      dockerfile: celery.dockerfile
#    restart: always
#    command: celery -A just_finance worker --beat --scheduler django --loglevel=info
#    volumes:
#      - .:/just_finance
#    depends_on:
#      - "db"
#      - "redis"
#    env_file: ./.env