# Generated by Django 4.0.4 on 2022-09-14 14:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=10000)),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='finance/')),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hr/')),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/')),
            ],
            bases=('core.base_models',),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tax/')),
            ],
            bases=('core.base_models',),
        ),
    ]
