# Generated by Django 4.0.4 on 2022-09-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='whatsapp',
            field=models.CharField(default=' ', max_length=200, verbose_name='Whatsapp'),
            preserve_default=False,
        ),
    ]
