# Generated by Django 4.0.4 on 2022-09-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_settings_twitter_settings_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtube'),
        ),
    ]
