# Generated by Django 4.0.4 on 2022-09-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_excell_template_setting_description_setting_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='excell_template',
            name='title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='excell_template',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='excell_template',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
