# Generated by Django 4.0.4 on 2022-10-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_excell_template_title_az_excell_template_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excell_template',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='excell_templates', to='core.applicationcategory', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
