# Generated by Django 4.0.4 on 2022-09-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
    ]
