# Generated by Django 4.0.4 on 2022-10-14 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_excell_template_title_az_excell_template_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
