# Generated by Django 4.0.4 on 2022-09-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
