# Generated by Django 4.0.4 on 2022-09-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('base_models_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base_models')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
            ],
            bases=('core.base_models',),
        ),
    ]
