# Generated by Django 4.0.4 on 2022-10-14 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_setting_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
