# Generated by Django 4.0.4 on 2022-10-22 10:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
