# Generated by Django 4.0.4 on 2022-10-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_service_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicefaq',
            options={'ordering': ['id']},
        ),
    ]
