# Generated by Django 4.0.4 on 2022-10-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_servicefaq_options'),
        ('core', '0009_alter_servicefaq_options_service_description_az_and_more'),
    ]

    operations = [
    ]
