# Generated by Django 4.0.4 on 2022-11-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20221028_1344'),
        ('core', '0010_merge_20221106_0914'),
    ]

    operations = [
    ]
