# Generated by Django 4.0.4 on 2022-10-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetype',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='sectortype',
            name='tax_type',
        ),
        migrations.RemoveField(
            model_name='taxtype',
            name='insurance_type',
        ),
        migrations.AddField(
            model_name='insurancetype',
            name='fees',
            field=models.ManyToManyField(to='calculator.insurancefee', verbose_name='Fees'),
        ),
        migrations.AddField(
            model_name='sectortype',
            name='tax_types',
            field=models.ManyToManyField(related_name='sector_types', to='calculator.taxtype'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='insurance_types',
            field=models.ManyToManyField(to='calculator.insurancetype', verbose_name='Insurance Types'),
        ),
    ]
