# Generated by Django 4.0.4 on 2022-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_insurancetype_fee_remove_sectortype_tax_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancefee',
            name='fee',
        ),
        migrations.AddField(
            model_name='insurancefee',
            name='calculate_formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
