# Generated by Django 4.0.4 on 2022-10-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_insurancefee_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tax Type Name',
                'verbose_name_plural': 'Tax Type Names',
            },
        ),
        migrations.RenameField(
            model_name='insurancefee',
            old_name='calculate_formula',
            new_name='from_to_formula',
        ),
        migrations.AddField(
            model_name='insurancefee',
            name='to_from_formula',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Calculator',
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.insurancetypename'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.taxtypename', verbose_name='Name'),
        ),
    ]
