# Generated by Django 4.0.4 on 2022-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_insurancetype_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetype',
            name='name',
            field=models.CharField(blank=True, choices=[('Sığortaolunan', 'Sığortaolunan'), ('Sığortaedən', 'Sığortaedən')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='name',
            field=models.CharField(blank=True, choices=[('Gəlir vergisi', 'Gəlir vergisi'), ('Sosial sığorta haqqı', 'Sosial sığorta haqqı'), ('İşsizlikdən sığorta haqqı', 'İşsizlikdən sığorta haqqı'), ('İcbari tibbi sığorta', 'İcbari tibbi sığorta')], max_length=255, null=True),
        ),
    ]
