# Generated by Django 4.0.4 on 2022-10-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_insurancetype_name_alter_taxtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectortype',
            name='name',
            field=models.CharField(choices=[('Neft-qaz sahəsində fəaliyyəti olmayan və qeyri-dövlət sektoruna aid edilən', 'Neft-qaz sahəsində fəaliyyəti olmayan və qeyri-dövlət sektoruna aid edilən'), ('Neft-qaz sahəsində fəaliyyəti olan və dövlət sektoruna aid edilən', 'Neft-qaz sahəsində fəaliyyəti olan və dövlət sektoruna aid edilən')], max_length=255),
        ),
    ]
