# Generated by Django 4.0.4 on 2022-10-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_sectortype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancefee',
            name='from_number',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insurancefee',
            name='to_number',
            field=models.FloatField(),
        ),
    ]
